### PR TITLE
Add TableTraits.jl integration

### PR DESCRIPTION
**Pull request by davidanthoff**
Don't merge yet, still some stuff to do.

In particular:
- [x] Handle missing values. Yeah, everyone's favorite topic. Mainly I need to understand how that is actually handled on the pandas side of things.
- [x] Wait until TableTraitsUtils.jl is registered JuliaLang/METADATA.jl#10822.

And then this will only start to properly work as soon as I've tagged another version of IterableTables.jl, but we don't have to wait for that.

### CODE REVIEW

**Comment by davidanthoff** [comment]
The missing value handling is not perfect yet, but I think good enough to merge and release at this point. I mostly followed [this](http://pandas.pydata.org/pandas-docs/stable/gotchas.html#na-type-promotions) guide.

Probably the case that is really annoying is that right now one can't convert an iterable table that has a ``String`` column that can be missing to a Pandas DataFrame.

**Comment by davidanthoff** [comment]
This PR only works on julia 0.6, so I bumped the min version for the whole package and adjusted travis accordingly. Lets see whether tests pass with that. You'll obviously need to make the call whether you are ready to drop julia 0.5 support.

**Comment by davidanthoff** [comment]
@malmaud Bump, any concerns with this PR?

**Comment by malmaud** [comment]
Sorry, I'll take a look soon.

**Comment by malmaud** [comment]
Looks good. Thanks!

**Comment by davidanthoff** [comment]
Great, thanks!

**Pull request merged**
