### PR TITLE
Update TableTraits.jl integration

### PR DESCRIPTION
**Pull request by davidanthoff**
Don't merge yet, this requires a new version of TableTraitsUtils.jl that is not yet merged. Mainly just wanted to let you know that you don't have to fix the integration, I'll take care of it :)

### CODE REVIEW

**Comment by davidanthoff** [comment]
I thought this should work now, but there seems to be some generic testing error related to numpy or something? Any idea what is going on there?

**Comment by tkf** [comment]
I think the CI error was fixed by #32.

**Comment by davidanthoff** [comment]
Alright, trying with a rebased version.

**Comment by davidanthoff** [comment]
Ok, I think this is ready to be merged.

**Comment by malmaud** [comment]
Great! Thanks!

**Pull request merged**
