### PR TITLE
Removed Ix indexer and updated Index/MultiIndex path

### LINKED ISSUE #64: _IXIndexer error with pandas 1.0.0
The latest pandas (v1.0.0) does not have `_IXIndexer` key anymore.  I reverted to pandas 0.25.3 as a workaround for now but I think Pandas.jl needs to catch up...

```
julia> using Pandas
[ Info: Precompiling Pandas [eadc2687-ae89-51f9-a5d9-86b5a6373a9c]
ERROR: InitError: KeyError: key "_IXIndexer" not found
Stacktrace:
 [1] getproperty(::PyObject, ::String) at /home/tkwong/.julia/packages/PyCall/ttONZ/src/PyCall.jl:308
 [2] (::Pandas.var"#21#24")() at /home/tkwong/.julia/packages/Pandas/wBpaf/src/Pandas.jl:216
 [3] __init__() at /home/tkwong/.julia/packages/Pandas/wBpaf/src/Pandas.jl:28``

### PR DESCRIPTION
**Pull request by tk3369**
Fixes #64

### CODE REVIEW

**Comment by sethaxen** [comment]
Is this still backwards-compatible with pre-1.0.0 pandas?

**Comment by sethaxen** [comment]
I've resolved the Travis errors on https://github.com/JuliaPy/Pandas.jl/pull/63.

**Comment by tk3369** [comment]
> Thanks for this fix! Is this still backwards-compatible with pre-1.0.0 pandas?

Technically, there are two changes in this PR:
1. Remove `_IXIndexer`
2. Update the python paths for `Index` and `MultiIndex`

The Ix indexer has been deprecated by Pandas for several years and finally they removed it in 1.0.0.  Since we're removing functionality, I would say it's backward compatible.  The second change is unlikely going to be compatible since the paths to find the Python classes are different.  

Unless we want to support both pre- and post-1.0 configurations with the same code, I would suggest that we put something in the README and ask people to pin the release if they need to use an older version of Pandas.

> I've resolved the Travis errors on #63.

I suppose that you mean the Travis error here :-)  I think the dependent Python package is `pytables` rather than `tables`.  I don't know much about the history but it seems that it's been renamed.  I can fix that with the same PR.

**Comment by tk3369** [comment]
Oh, I see what you mean about the Travis fix in #63.

It seems odd that it used to work before.
https://travis-ci.org/JuliaPy/Pandas.jl/jobs/556473084?utm_medium=notification&utm_source=github_status

P.S. I was a bit confused earlier.  It looks like the package is named `tables` for pip but `pytables` for conda.  Another reason why we like Julia 😄

**Comment by sethaxen** [comment]
> It seems odd that it used to work before.
> https://travis-ci.org/JuliaPy/Pandas.jl/jobs/556473084?utm_medium=notification&utm_source=github_status

Yes, although that was 7 months ago. One of the dependencies could have changed, or as has happened to me before, Travis could have changed something with their setup.

**Comment by sethaxen** [comment]
@malmaud it would be great to get this and #63 merged soon with a new release. I have a package that depends on Pandas.jl that currently can't be used with pandas 1.0.0.

**Comment by malmaud** [comment]
Ok, I'll check it out today.

**Comment by sethaxen** [comment]
Thanks!

**Comment by malmaud** [comment]
Thanks for this PR! If it's not too hard, I think I'd like to see if we can get this backwards-compatible. I'll try adding a commit to this since it doesn't look like it will be too hard.

**Comment by tk3369** [comment]
That's great!  It's the best of both worlds!  Thanks @malmaud

**Pull request merged**
